# eslint-disable pnpm/yaml-enforce-settings
packages: []

catalogs:

  build:
    '@mdx-js/rollup': ^3.1.1
    '@shikijs/rehype': ^1.25.0
    '@tanstack/router-plugin': ^1.149.0
    '@unocss/eslint-config': ^66.5.12
    '@unocss/preset-attributify': ^66.5.12
    '@unocss/preset-web-fonts': ^66.5.12
    '@vitejs/plugin-react': ^5.1.2
    beasties: ^0.3.5
    unocss: ^66.5.12
    vite: ^7.3.0
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.3.3

  dev:
    '@antfu/eslint-config': ^6.7.3
    '@eslint-react/eslint-plugin': ^2.5.1
    '@iconify-json/carbon': ^1.2.8
    '@testing-library/react': ^16.3.1
    cypress: ^15.8.2
    cypress-vite: ^1.8.0
    eslint: ^9.39.2
    eslint-plugin-cypress: ^5.2.1
    eslint-plugin-format: ^1.2.0
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    https-localhost: ^4.7.1
    js-yaml: ^4.1.1
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.12.1
    taze: ^19.0.2
    typescript: ^5.8.2
    vitest: ^4.0.16

  frontend:
    '@tanstack/react-router': ^1.147.3
    '@unhead/react': ^2.1.1
    '@unocss/reset': ^66.5.12
    i18next: ^25.7.3
    i18next-browser-languagedetector: ^8.2.0
    i18next-http-backend: ^3.0.2
    nprogress: ^0.2.0
    react: ^19.2.3
    react-dom: ^19.2.3
    react-i18next: ^16.5.1
    zustand: ^5.0.9

  types:
    '@types/js-yaml': ^4.0.9
    '@types/mdx': ^2.0.13
    '@types/nprogress': ^0.2.3
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3

onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
