/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as DefaultRouteImport } from './routes/_default'
import { Route as R404RouteImport } from './routes/_404'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as DefaultAboutRouteImport } from './routes/_default/about'
import { Route as R404SplatRouteImport } from './routes/_404/$'
import { Route as DefaultHiNameRouteImport } from './routes/_default/hi/$name'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultRoute = DefaultRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/_404',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const DefaultAboutRoute = DefaultAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DefaultRoute,
} as any)
const R404SplatRoute = R404SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => R404Route,
} as any)
const DefaultHiNameRoute = DefaultHiNameRouteImport.update({
  id: '/hi/$name',
  path: '/hi/$name',
  getParentRoute: () => DefaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof R404SplatRoute
  '/about': typeof DefaultAboutRoute
  '/': typeof HomeIndexRoute
  '/hi/$name': typeof DefaultHiNameRoute
}
export interface FileRoutesByTo {
  '/$': typeof R404SplatRoute
  '/about': typeof DefaultAboutRoute
  '/': typeof HomeIndexRoute
  '/hi/$name': typeof DefaultHiNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_404': typeof R404RouteWithChildren
  '/_default': typeof DefaultRouteWithChildren
  '/_home': typeof HomeRouteWithChildren
  '/_404/$': typeof R404SplatRoute
  '/_default/about': typeof DefaultAboutRoute
  '/_home/': typeof HomeIndexRoute
  '/_default/hi/$name': typeof DefaultHiNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/about' | '/' | '/hi/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/about' | '/' | '/hi/$name'
  id:
    | '__root__'
    | '/_404'
    | '/_default'
    | '/_home'
    | '/_404/$'
    | '/_default/about'
    | '/_home/'
    | '/_default/hi/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404RouteWithChildren
  DefaultRoute: typeof DefaultRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_default': {
      id: '/_default'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DefaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_404': {
      id: '/_404'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_default/about': {
      id: '/_default/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DefaultAboutRouteImport
      parentRoute: typeof DefaultRoute
    }
    '/_404/$': {
      id: '/_404/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof R404SplatRouteImport
      parentRoute: typeof R404Route
    }
    '/_default/hi/$name': {
      id: '/_default/hi/$name'
      path: '/hi/$name'
      fullPath: '/hi/$name'
      preLoaderRoute: typeof DefaultHiNameRouteImport
      parentRoute: typeof DefaultRoute
    }
  }
}

interface R404RouteChildren {
  R404SplatRoute: typeof R404SplatRoute
}

const R404RouteChildren: R404RouteChildren = {
  R404SplatRoute: R404SplatRoute,
}

const R404RouteWithChildren = R404Route._addFileChildren(R404RouteChildren)

interface DefaultRouteChildren {
  DefaultAboutRoute: typeof DefaultAboutRoute
  DefaultHiNameRoute: typeof DefaultHiNameRoute
}

const DefaultRouteChildren: DefaultRouteChildren = {
  DefaultAboutRoute: DefaultAboutRoute,
  DefaultHiNameRoute: DefaultHiNameRoute,
}

const DefaultRouteWithChildren =
  DefaultRoute._addFileChildren(DefaultRouteChildren)

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404RouteWithChildren,
  DefaultRoute: DefaultRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
